/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bases/templates/tables/templates/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get templates records
         * @description Get templates records
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description record data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            records: components["schemas"]["Record"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create templates record
         * @description Create templates record
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        values: {
                            Title: string;
                            Cover?: ({
                                id: string;
                                url: string;
                                signedUrl?: string | null;
                                name: string;
                                token: string;
                                size: number;
                                type: string;
                            }[] | null) | {
                                /** @enum {string} */
                                type: "set";
                                value: {
                                    id: string;
                                    url: string;
                                    signedUrl?: string | null;
                                    name: string;
                                    token: string;
                                    size: number;
                                    type: string;
                                }[] | null;
                            } | unknown;
                            baseId: string;
                            spaceId: string;
                            Images?: ({
                                id: string;
                                url: string;
                                signedUrl?: string | null;
                                name: string;
                                token: string;
                                size: number;
                                type: string;
                            }[] | null) | {
                                /** @enum {string} */
                                type: "set";
                                value: {
                                    id: string;
                                    url: string;
                                    signedUrl?: string | null;
                                    name: string;
                                    token: string;
                                    size: number;
                                    type: string;
                                }[] | null;
                            } | unknown;
                            Summary?: string | null;
                        };
                    };
                };
            };
            responses: {
                /** @description Record Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Bulk delete templates records
         * @description Bulk delete templates records
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        filter: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description record data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deletedCount: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Bulk update templates records
         * @description Bulk update templates records
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        filter: Record<string, never>;
                        values: {
                            Title?: string;
                            Cover?: ({
                                id: string;
                                url: string;
                                signedUrl?: string | null;
                                name: string;
                                token: string;
                                size: number;
                                type: string;
                            }[] | null) | {
                                /** @enum {string} */
                                type: "set";
                                value: {
                                    id: string;
                                    url: string;
                                    signedUrl?: string | null;
                                    name: string;
                                    token: string;
                                    size: number;
                                    type: string;
                                }[] | null;
                            } | unknown;
                            baseId?: string;
                            spaceId?: string;
                            Images?: ({
                                id: string;
                                url: string;
                                signedUrl?: string | null;
                                name: string;
                                token: string;
                                size: number;
                                type: string;
                            }[] | null) | {
                                /** @enum {string} */
                                type: "set";
                                value: {
                                    id: string;
                                    url: string;
                                    signedUrl?: string | null;
                                    name: string;
                                    token: string;
                                    size: number;
                                    type: string;
                                }[] | null;
                            } | unknown;
                            Summary?: string | null;
                        };
                    };
                };
            };
            responses: {
                /** @description records updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkUpdateRecordsOutput"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/bases/templates/tables/templates/records/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get templates record by id
         * @description Get templates record by id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    recordId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description record data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Record"] & unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete templates record by id
         * @description Delete templates record by id
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    recordId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description record data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update templates record
         * @description Update templates record
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    recordId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        values: {
                            Title?: string;
                            Cover?: ({
                                id: string;
                                url: string;
                                signedUrl?: string | null;
                                name: string;
                                token: string;
                                size: number;
                                type: string;
                            }[] | null) | {
                                /** @enum {string} */
                                type: "set";
                                value: {
                                    id: string;
                                    url: string;
                                    signedUrl?: string | null;
                                    name: string;
                                    token: string;
                                    size: number;
                                    type: string;
                                }[] | null;
                            } | unknown;
                            baseId?: string;
                            spaceId?: string;
                            Images?: ({
                                id: string;
                                url: string;
                                signedUrl?: string | null;
                                name: string;
                                token: string;
                                size: number;
                                type: string;
                            }[] | null) | {
                                /** @enum {string} */
                                type: "set";
                                value: {
                                    id: string;
                                    url: string;
                                    signedUrl?: string | null;
                                    name: string;
                                    token: string;
                                    size: number;
                                    type: string;
                                }[] | null;
                            } | unknown;
                            Summary?: string | null;
                        };
                    };
                };
            };
            responses: {
                /** @description Record Updated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/bases/templates/tables/templates/records/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk create templates record
         * @description Bulk create templates record
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        records: {
                            id?: string;
                            values: {
                                Title: string;
                                Cover?: ({
                                    id: string;
                                    url: string;
                                    signedUrl?: string | null;
                                    name: string;
                                    token: string;
                                    size: number;
                                    type: string;
                                }[] | null) | {
                                    /** @enum {string} */
                                    type: "set";
                                    value: {
                                        id: string;
                                        url: string;
                                        signedUrl?: string | null;
                                        name: string;
                                        token: string;
                                        size: number;
                                        type: string;
                                    }[] | null;
                                } | unknown;
                                baseId: string;
                                spaceId: string;
                                Images?: ({
                                    id: string;
                                    url: string;
                                    signedUrl?: string | null;
                                    name: string;
                                    token: string;
                                    size: number;
                                    type: string;
                                }[] | null) | {
                                    /** @enum {string} */
                                    type: "set";
                                    value: {
                                        id: string;
                                        url: string;
                                        signedUrl?: string | null;
                                        name: string;
                                        token: string;
                                        size: number;
                                        type: string;
                                    }[] | null;
                                } | unknown;
                                Summary?: string | null;
                            };
                        }[];
                    };
                };
            };
            responses: {
                /** @description Record Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            createdCount: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bases/templates/tables/templates/records/{recordId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate templates record by id
         * @description Duplicate templates record by id
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    recordId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description record data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recordId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bases/templates/tables/templates/records/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk duplicate templates records
         * @description Bulk duplicate templates records
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        filter: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description records updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkDuplicateRecordsOutput"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bases/templates/tables/templates/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe templates record events
         * @description Subscribe templates record events
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description subscription event schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": {
                            event?: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example rechc0mi1ar */
        RecordId: string;
        /** @example {
         *       "Title": "Project Management",
         *       "Cover": [
         *         {
         *           "id": "01915fcd-fcc3-7222-a5c1-842cf2ab8b26",
         *           "url": "https://minio-igkkokwwgwk0kw0s0gok00cw.undb.io/undb-private/01915fcd-fcc3-7222-a5c1-842cf2ab8b26.jpg",
         *           "signedUrl": "https://minio-igkkokwwgwk0kw0s0gok00cw.undb.io/undb-private/01915fcd-fcc3-7222-a5c1-842cf2ab8b26.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Mv5UqoUhDirVxpCEbEc7%2F20240817%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240817T114951Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=380e0d78cfb5286a4bbab5c9bf88d594e98bf484b48c95abf95ed17cbffba1a5",
         *           "name": "01915fcd-fcc3-7222-a5c1-842cf2ab8b26.jpg",
         *           "token": "HP6hgqx482-fwDJS",
         *           "size": 2628885,
         *           "type": "image/jpeg"
         *         }
         *       ],
         *       "baseId": "basry3lfnco",
         *       "spaceId": "spam88h5",
         *       "Images": [],
         *       "Summary": "This project management template is designed to help teams efficiently manage tasks, timelines, and resources using Airtable. It includes essential features like task tracking, where you can log task names, assign team members, set priorities, deadlines, and monitor status. The template provides various views, such as Kanban and calendar views, to visualize project progress and keep the team aligned. It also supports team collaboration by allowing members to assign tasks, add comments, and share attachments. Additionally, it helps track project resources like budgets, time, and tools, ensuring projects stay on track. The template is versatile and can be adapted to manage anything from simple task lists to complex multi-project management."
         *     } */
        RecordValues: {
            id: string;
            Title: string;
            createdAt: string;
            createdBy: string;
            updatedAt: string;
            updatedBy: string;
            autoIncrement: number;
            Cover: {
                id: string;
                url: string;
                signedUrl?: string | null;
                name: string;
                token: string;
                size: number;
                type: string;
            }[];
            baseId: string;
            spaceId: string;
            Images?: {
                id: string;
                url: string;
                signedUrl?: string | null;
                name: string;
                token: string;
                size: number;
                type: string;
            }[] | null;
            Summary?: string | null;
        };
        /** @example {} */
        RecordDisplayValues: {
            createdBy?: unknown;
            updatedBy?: unknown;
        };
        Record: {
            id: components["schemas"]["RecordId"];
            values: components["schemas"]["RecordValues"];
            displayValues: components["schemas"]["RecordDisplayValues"];
        };
        /** @description records count that has been updated */
        BulkUpdateRecordsOutput: {
            modifiedCount: number;
        };
        /** @description records count that has been updated */
        BulkDuplicateRecordsOutput: {
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
